---
name: Build and Release
on:
  release:
    types: [created]
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v4
      - name: Update the version
        run: |-
          sed -i 's/Version: v[0-9]*\.[0-9]*\.[0-9]*/Version: ${{github.event.release.name}}/g' main.go
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.22.0
          extra_files: LICENSE README.md
